// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACiANmsWsBSY6nd4iDVeAFmkY_f38FLiE',
    appId: '1:495134791302:web:770aac486b6a8b7e3ce307',
    messagingSenderId: '495134791302',
    projectId: 'edubro-4c60a',
    authDomain: 'edubro-4c60a.firebaseapp.com',
    storageBucket: 'edubro-4c60a.appspot.com',
    measurementId: 'G-FER845V5BD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD5ClTKqZu3GOX6Ujo6B26eAPePQ6GUmc',
    appId: '1:495134791302:android:f2d620d4a88bb4f33ce307',
    messagingSenderId: '495134791302',
    projectId: 'edubro-4c60a',
    storageBucket: 'edubro-4c60a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEUacSGj4WTMB4jLVUFQcpdgFLUVRmhrc',
    appId: '1:495134791302:ios:02d8ae20af64c0373ce307',
    messagingSenderId: '495134791302',
    projectId: 'edubro-4c60a',
    storageBucket: 'edubro-4c60a.appspot.com',
    iosClientId:
        '495134791302-tmckp6gur5jvth3jumj9u8nnpc9sbj1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.cr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEUacSGj4WTMB4jLVUFQcpdgFLUVRmhrc',
    appId: '1:495134791302:ios:02d8ae20af64c0373ce307',
    messagingSenderId: '495134791302',
    projectId: 'edubro-4c60a',
    storageBucket: 'edubro-4c60a.appspot.com',
    iosClientId:
        '495134791302-tmckp6gur5jvth3jumj9u8nnpc9sbj1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.cr',
  );
}
